# Generated by Django 4.0.7 on 2022-12-06 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbmany', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='inviter',
        ),
    ]
