# Generated by Django 4.0.7 on 2022-12-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmany', '0002_remove_group_members_remove_membership_inviter'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='groups',
            field=models.ManyToManyField(through='dbmany.Membership', to='dbmany.group'),
        ),
    ]
