# Generated by Django 4.0.7 on 2022-12-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmany', '0004_membership_inviter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='invite_reason',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='inviter',
        ),
        migrations.AlterField(
            model_name='person',
            name='groups',
            field=models.ManyToManyField(related_name='groups', through='dbmany.Membership', to='dbmany.group'),
        ),
    ]
