# Generated by Django 4.0.7 on 2022-12-12 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmany', '0005_remove_membership_invite_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(through='dbmany.Membership', to='dbmany.person'),
        ),
        migrations.AddField(
            model_name='membership',
            name='invite_reason',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='person',
            name='groups',
            field=models.ManyToManyField(through='dbmany.Membership', to='dbmany.group'),
        ),
    ]
