# Generated by Django 4.0.7 on 2022-12-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmany', '0006_group_members_membership_invite_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='invite_reason',
            field=models.CharField(default='', max_length=64),
        ),
    ]
